### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Nikolai980** [Hadi-koubeissi/discord-web-api#2]
Can you tell me how to add 4 owners in the const owners

**Comment by hadi-4100** [comment]
`const owners = [
 {
 id: "442793591501357056",
 post: "Bot Owner",
 GHURL: "https://github.com/Hadi-Koubeissi",
 InstaURL: "",
 YTURL: "https://www.youtube.com/channel/UCmO0xdpxQr7fX2Csth_2JOQ",
 },
{
 id: "user iD 2",
 post: "Bot Owner",
 GHURL: "https://github.com/Hadi-Koubeissi",
 InstaURL: "",
 YTURL: "https://www.youtube.com/channel/UCmO0xdpxQr7fX2Csth_2JOQ",
 },
];`

**Comment by r4club** [comment]
Thank you I need to try this then close the issues.

**Comment by Nikolai980** [comment]
Not working only shows the first user.
![IMG_20220131_160126](https://user-images.githubusercontent.com/74131129/151817345-6482cde3-25b9-4dc4-84ce-d6968beed06a.jpg)
